import { IExperience, Months, Stack } from "../types"

export const experience: Array<IExperience> = [
	{
		position: "Frontend React Developer",
		organization: "Gräbert GmbH",
		description: "Developing frontend for ARES Kudo using React and MUI.",
		city: "Berlin",
		country: "Germany",
		yearFrom: 2024,
		monthFrom: Months.Aug,
		website: "https://www.graebert.com/",
		stack: [
			Stack.React,
			Stack.MUI,
			Stack.TypeScript,
			Stack.Flux,
			Stack.Vite,
			Stack.BitBucket,
			Stack.Jira,
		],
	},
	{
		position: "Frontend React Developer",
		organization: "MetaLamp",
		description: "Developed a hotel booking website.",
		city: "Yerevan",
		country: "Armenia",
		yearFrom: 2024,
		monthFrom: Months.Mar,
		yearTo: 2024,
		monthTo: Months.Aug,
		website: "https://metalamp.ru/",
		stack: [
			Stack.React,
			Stack.Next,
			Stack.TypeScript,
			Stack.Webpack,
			Stack.Redux,
			Stack.SCSS,
			Stack.Pug,
			Stack.Gitlab,
			Stack.Firebase,
			Stack.Scrum,
		],
	},
	{
		position: "React Web Engineer",
		organization: "Martspec LLC",
		description:
			"I developed and maintained a website for a product company that develops applications for Apple Watch.",
		city: "Austin",
		country: "USA",
		yearFrom: 2023,
		monthFrom: Months.Jun,
		yearTo: 2024,
		monthTo: Months.Jun,
		website: "https://martspec.com",
		stack: [
			Stack.React,
			Stack.Webpack,
			Stack.TypeScript,
			Stack.Git,
			Stack.SCSS,
			Stack.Bootstrap,
		],
	},
	{
		position: "Frontend Developer",
		organization: "Freelance",
		description:
			"Frontend developing using React+Redux+TS as well as HTML+CSS+JS for customers. Check my GitHub to see completed projects.",
		city: "Yerevan",
		country: "Armenia",
		yearFrom: 2022,
		monthFrom: Months.Dec,
	},
	{
		position: ".NET Support Developer",
		organization: "Developer Express Inc.",
		description:
			"Customer Support in English. I Provided recommendations to customers on using the company's products to solve specific tasks. Wrote bug reports and address issues. Demonstrated the product's functionality to users using personal demo projects.",
		city: "Yerevan",
		country: "Armenia",
		yearFrom: 2022,
		monthFrom: Months.Aug,
		yearTo: 2022,
		monthTo: Months.Dec,
		website: "https://www.devexpress.com",
	},
	{
		position: "Developer",
		organization: "Strizhament",
		description:
			'I supported and customized 1C:Retail 2.3 for the "Vinoteka Strizhament" store chain. During this time, I configured synchronization with the "Vinoteka Strizhament" mobile application via REST API, Set up synchronization between 1C: Retail and the Bitrix website (rewriting 40% of the integration module), Reduced the number of support requests from employees in 70 stores by 50% by resolving configuration errors in the 1C: Retail system, Configured MS SQL Server and implemented database backup procedures, Managed the transition of the store chain to 1C: Retail during a merger.',
		city: "Stavropol",
		country: "Russia",
		yearFrom: 2021,
		monthFrom: Months.Jul,
		yearTo: 2022,
		monthTo: Months.Jul,
		website: "https://strizament-vinoteka.ru",
	},
]
