export const Stack = {
	BitBucket: "BitBucket",
	Bootstrap: "Bootstrap",
	CSS: "CSS",
	Firebase: "Firebase",
	Flux: "Flux",
	Git: "Git",
	Gitlab: "Gitlab",
	HTML: "HTML",
	Jira: "Jira",
	JavaScript: "JavaScript",
	MUI: "MUI",
	Next: "Next.js",
	Node: "Node.js",
	Pug: "Pug",
	PurgeCSS: "PurgeCSS",
	React: "React",
	ReactRouter: "React Router",
	Redux: "Redux",
	ReduxToolkit: "Redux Toolkit",
	SASS: "SASS",
	SCSS: "SCSS",
	Scrum: "SCRUM",
	TypeScript: "TypeScript",
	Vite: "Vite",
	Webpack: "Webpack",
	CSharp: "C#",
	DotNet: ".NET",
	OOP: "OOP",
	DevExpress: "DevExpress",
	CustomerSupport: "Customer Support",
} as const

export const Months = {
	Jan: "Jan",
	Feb: "Feb",
	Mar: "Mar",
	Apr: "Apr",
	May: "May",
	Jun: "Jun",
	Jul: "Jul",
	Aug: "Aug",
	Sep: "Sep",
	Oct: "Oct",
	Nov: "Nov",
	Dec: "Dec",
} as const
